name: "style-nfsd"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-camera-datamodule"
data:
  batch_size: [1, 1]
  width: [128, 256]
  height: [128, 256]
  resolution_milestones: [5000]
  elevation_range: [-10, 45]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  n_val_views: 48

system_type: "nfsd-style-system"
system:
  geometry_type: "implicit-volume"
  geometry:
    radius: 1.0
    normal_type: "analytic"

  material_type: "no-material"
  material:
    n_output_dims: 3
    color_activation: sigmoid
    requires_normal: true

  # # Learn bacgkground
  # background_type: "neural-environment-map-background"
  # background:
  #   color_activation: sigmoid
  #   random_aug: true
  
  # Use solid color background
  background_type: "solid-color-background"
  background:
    n_output_dims: 3
    color: [0.0, 0.0, 0.0]  # black

  renderer_type: "nerf-volume-renderer"
  renderer:
    radius: ${system.geometry.radius}
    num_samples_per_ray: 512
    return_comp_normal: true

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: "a toy car"

  guidance_type: "nfsd-styled-guidance"
  guidance:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    guidance_scale: 7.5
    weighting_strategy: sds
    min_step_percent: 0.3
    max_step_percent: 0.98
    sqrt_anneal: true
    use_img_loss: true

    style_activate_layer_indices: [[ 22,32 ] ]
    style_activate_step_indices: [[0, 40]]
    style_image_path: "custom/dream-in-style/images/a_fire_on_a_black_background.png"
    style_image_size: 512
    style_blip_object: null
    guidance_scale_style: 7.5

    style_ratio_use: true
    style_ratio_scheduler_type: "sqrt"
    style_ratio_start_scale: 0.0
    style_ratio_end_scale: 1.0

  loggers:
    wandb:
      enable: true
      project: "default"
      name: "${rmspace:${system.prompt_processor.prompt},_}"

  loss:
    lambda_sds: 1.
    lambda_sds_img: 0.01
    lambda_orient: 0.
    lambda_sparsity: 25.
    lambda_opaque: [10000, 0.0, 1000.0, 10001]
    lambda_z_variance: 300.

  optimizer:
    name: Adam
    args:
      lr: 0.01
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry.encoding:
        lr: 0.01
      geometry.density_network:
        lr: 0.001
      geometry.feature_network:
        lr: 0.001
      background:
        lr: 0.001

trainer:
  max_steps: 25000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 500
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: 5000
